# Builds devtools base image "creator-base" which pre-installs python and all
# binary dependencies. This makes each derived image much faster to build, even
# when using QEMU emulation.
ARG EE_BASE_IMAGE=quay.io/fedora/fedora-minimal:37
FROM $EE_BASE_IMAGE

# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.source https://github.com/ansible/creator-ee/blob/main/base/Containerfile
LABEL org.opencontainers.image.authors "Ansible DevTools"
LABEL org.opencontainers.image.vendor "Red Hat"
LABEL org.opencontainers.image.licenses "GPL-3.0"

USER root

RUN \
microdnf update -y && \
microdnf -y upgrade && \
microdnf install -y \
dumb-init \
git \
podman \
&& microdnf clean all
