# Builds devtools base image "creator-base" which pre-installs python and all
# binary dependencies. This makes each derived image much faster to build, even
# when using QEMU emulation.
ARG EE_BASE_IMAGE=quay.io/fedora/fedora:latest
FROM $EE_BASE_IMAGE
USER root

RUN \
dnf update -y && \
dnf -y upgrade && \
dnf install -y \
git \
podman \
python3-cffi \
python3-cryptography \
python3-pip \
python3-pyrsistent \
python3-pyyaml \
python3-ruamel-yaml \
python3-wheel \
&& dnf autoremove
