---
collections:
  - name: ansible.posix
  - name: ansible.windows
  - name: awx.awx
  - name: containers.podman
  - name: kubernetes.core
  - name: redhatinsights.insights
  - name: theforeman.foreman
