---
name: CI

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

concurrency:
  group: >-
    ${{
        github.workflow
    }}-${{
        github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  podman:
    name: ${{ matrix.toxenv }}

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        toxenv:
        - podman
        - docker

    env:
      TOXENV: ${{ matrix.toxenv }},check-diff

    steps:
    - name: Grab the source from Git
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install tox
      run: python -m pip install tox

    - name: Prepare ${{ env.TOXENV }} tox testenv
      run: tox --skip-missing-interpreters false --notest

    - name: Run ${{ env.TOXENV }} tox testenv
      run: tox --skip-missing-interpreters false
...
